---
- hosts: TFG
  sudo: yes
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes

    - name: Install apache
      apt:
        name: apache2
        state: present

    - name: Install mongo
      apt:
        name: mongodb
        state: present

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Python 2.7
      apt:
        name: python2.7
        state: present
