---
- hosts: TFG
  sudo: yes
  tasks:
    - name: Update Apt cache
      apt: update_cache=yes

    # Instalamos pip y diversas herramientas para la gestión del servidor como docker-py
    - name: Install pip
      apt:
        name: python3-setuptools
        state: present

    - name : easy install
      command: easy_install3 pip

    - name : upgrade pip
      command : pip install --upgrade pip

    - pip:
        name: docker-py

      # Instalamos docker
    - name: Install docker.io
      apt:
        name: docker.io
        state: present
      # Conectqamos con ASW container ( falta añadir el comando ya que se renueva cada día)
    - name: Connect to ASW Container
      command: |
        docker login -u AWS -p

      # Descargamos e iniciamos los contenedores que tenemos alojados en ASW Container
    - name: Download latest Docker images mongo
      command: docker run --name mongo -d 207646075765.dkr.ecr.us-east-2.amazonaws.com/organizat-mongo

    - name: Download latest Docker images organizat-web
      command: docker run --name server-web-dev -p 3000:3000 -d 207646075765.dkr.ecr.us-east-2.amazonaws.com/organizat

    - name: Download latest Docker images organizat-hogar
      command: docker run --name server_hogar_dev -p 3001:3001 -d 207646075765.dkr.ecr.us-east-2.amazonaws.com/organizat-hogar

    - name: Download latest Docker images organizat-usuarios
      command: docker run --name server-usuario-dev -p 3002:3002 -d 207646075765.dkr.ecr.us-east-2.amazonaws.com/organizat-usuarios

      #Instalamos gcc y make para poder installar no-ip
    - name: Install gcc
      apt:
        name: gcc
        state: present

    - name: Install make
      apt:
        name: make
        state: present

      # Descargamos descomprimimos noip
    - name: Install no-ip 1
      command : wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz
      args :
        chdir: /usr/local/src/

    - name: Install no-ip 2
      command : tar xf noip-duc-linux.tar.gz
      args :
        chdir: /usr/local/src/
