---
- hosts: TFG
  sudo: yes
  tasks:
     - name: stop container
       docker_container:
        name: mongo
        state: stopped

     - name: stop container
       docker_container:
        name: server-web-dev
        state: stopped

     - name: stop container
       docker_container:
        name: server_hogar_dev
        state: stopped

     - name: stop container
       docker_container:
        name: server-usuario-dev
        state: stopped

     - name: start container
       docker_container:
        name: mongo
        state: started

     - name: start container
       docker_container:
        name: server-web-dev
        state: started

     - name: start container
       docker_container:
        name: server_hogar_dev
        state: started

     - name: start container
       docker_container:
        name: server-usuario-dev
        state: started

     - name: Iniciar no-ip
       command: ./noip2
       args :
        chdir: /usr/local/src/noip-2.1.9-1/

