---
- hosts: TFG
  sudo: yes
  tasks:
     - name: stop container
       docker_container:
        name: server-usuario-dev
        state: stopped

     - name: remove container
       docker_container:
        name: server-usuario-dev
        state: absent

     - name: Remove image
       docker_image:
        state: absent
        name: 207646075765.dkr.ecr.us-east-2.amazonaws.com/organizat-usuarios
        tag: latest

     - name: Connect to ASW Container
       command: |
        docker login -u AWS -p

     - name: Download latest Docker images organizat-ususarios
       command: docker run --name server-usuario-dev -p 3002:3002 -d 207646075765.dkr.ecr.us-east-2.amazonaws.com/organizat-usuarios
